
import { motion } from 'framer-motion';
import { Calendar, Clock, MapPin, Navigation, Copy, Check, Link as LinkIcon, Briefcase } from 'lucide-react';
import { useState } from 'react';
import { encodeItineraryToUrl } from '../utils/sharing';
import { BusinessShareModal } from './BusinessShareModal';

interface Activity {
    time: string;
    title: string;
    description: string;
    location: string;
}

interface DayPlan {
    day: number;
    title: string;
    activities: Activity[];
}

interface ItineraryResultProps {
    data: {
        days: DayPlan[];
    } | null;
}



export const ItineraryResult = ({ data }: ItineraryResultProps) => {
    const [copied, setCopied] = useState(false);
    const [shared, setShared] = useState(false);
    const [showBusinessModal, setShowBusinessModal] = useState(false);

    if (!data) return null;

    const formatItinerary = () => {
        let text = "AI GENERATED TRAVEL ITINERARY\n";
        text += "=".repeat(50) + "\n\n";

        data.days.forEach((day) => {
            text += `DAY ${day.day}: ${day.title} \n`;
            text += "-".repeat(50) + "\n\n";

            day.activities.forEach((activity) => {
                text += `${activity.title} \n`;
                text += `Time: ${activity.time} \n`;
                text += `Location: ${activity.location} \n`;
                text += `${activity.description} \n\n`;
            });

            text += "\n";
        });

        text += "=".repeat(50) + "\n";
        text += "Generated by AI Travel Planner\n";

        return text;
    };

    const copyToClipboard = async () => {
        try {
            const formattedText = formatItinerary();
            await navigator.clipboard.writeText(formattedText);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const shareLink = async () => {
        try {
            const url = encodeItineraryToUrl(data);
            await navigator.clipboard.writeText(url);
            setShared(true);
            setTimeout(() => setShared(false), 2000);
        } catch (err) {
            console.error('Failed to share:', err);
        }
    };

    return (
        <div className="w-full max-w-4xl mx-auto px-4 sm:px-6 py-4 sm:py-6">
            <BusinessShareModal
                isOpen={showBusinessModal}
                onClose={() => setShowBusinessModal(false)}
                data={data}
            />

            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 sm:mb-8">
                <div className="flex items-center gap-2 sm:gap-3">
                    <div className="w-1.5 sm:w-2 h-6 sm:h-8 bg-ai-accent rounded-full animate-pulse" />
                    <h2 className="text-xl sm:text-2xl font-bold text-white">AI Generated Plan</h2>
                </div>

                <div className="flex flex-wrap gap-3">
                    <button
                        onClick={() => setShowBusinessModal(true)}
                        className="flex items-center gap-2 px-4 py-2 bg-ai-accent/10 hover:bg-ai-accent/20 border border-ai-accent/30 hover:border-ai-accent rounded-lg text-ai-accent text-sm font-medium transition-all hover:scale-105 group whitespace-nowrap"
                    >
                        <Briefcase className="w-4 h-4" />
                        <span>Share as Business</span>
                    </button>

                    <button
                        onClick={shareLink}
                        className="flex items-center gap-2 px-4 py-2 bg-ai-card hover:bg-ai-card/80 border border-ai-accent/30 hover:border-ai-accent rounded-lg text-white text-sm font-medium transition-all hover:scale-105 group whitespace-nowrap"
                    >
                        {shared ? (
                            <>
                                <Check className="w-4 h-4 text-ai-accent" />
                                <span className="text-ai-accent">Copied!</span>
                            </>
                        ) : (
                            <>
                                <LinkIcon className="w-4 h-4 group-hover:text-ai-accent transition-colors" />
                                <span>Share</span>
                            </>
                        )}
                    </button>

                    <button
                        onClick={copyToClipboard}
                        className="flex items-center gap-2 px-4 py-2 bg-ai-card hover:bg-ai-card/80 border border-ai-accent/30 hover:border-ai-accent rounded-lg text-white text-sm font-medium transition-all hover:scale-105 group whitespace-nowrap"
                    >
                        {copied ? (
                            <>
                                <Check className="w-4 h-4 text-ai-accent" />
                                <span className="text-ai-accent">Copied!</span>
                            </>
                        ) : (
                            <>
                                <Copy className="w-4 h-4 group-hover:text-ai-accent transition-colors" />
                                <span>Copy Text</span>
                            </>
                        )}
                    </button>
                </div>
            </div>

            <div className="space-y-6 sm:space-y-8">
                {data.days.map((day, index) => (
                    <motion.div
                        key={day.day}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.2 }}
                        className="relative pl-4 sm:pl-6 md:pl-8 border-l-2 border-ai-muted/20"
                    >
                        <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-ai-secondary border-4 border-ai-dark" />

                        <h3 className="text-lg sm:text-xl font-bold text-ai-accent mb-3 sm:mb-4 flex items-center gap-2 flex-wrap">
                            <Calendar className="w-4 h-4 sm:w-5 sm:h-5 flex-shrink-0" />
                            <span className="break-words">Day {day.day}: {day.title}</span>
                        </h3>

                        <div className="space-y-3 sm:space-y-4">
                            {day.activities.map((activity, i) => (
                                <div key={i} className="glass p-3 sm:p-4 rounded-xl hover:bg-ai-card/60 transition-colors group">
                                    <div className="flex flex-col gap-2 mb-2">
                                        <h4 className="font-bold text-base sm:text-lg text-white group-hover:text-ai-accent transition-colors break-words">
                                            {activity.title}
                                        </h4>
                                        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 text-xs sm:text-sm text-ai-muted">
                                            <span className="flex items-center gap-1">
                                                <Clock className="w-3 h-3 sm:w-4 sm:h-4 flex-shrink-0" />
                                                <span className="break-words">{activity.time}</span>
                                            </span>
                                            <span className="flex items-center gap-1">
                                                <MapPin className="w-3 h-3 sm:w-4 sm:h-4 flex-shrink-0" />
                                                <span className="break-words">{activity.location}</span>
                                            </span>
                                        </div>
                                    </div>
                                    <p className="text-gray-400 text-xs sm:text-sm leading-relaxed break-words">{activity.description}</p>
                                </div>
                            ))}
                        </div>
                    </motion.div>
                ))}
            </div>

            <div className="mt-6 sm:mt-8 flex justify-center px-4">
                <a
                    href="https://www.google.com/travel/flights?q=flights+to+Bagdogra"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 px-4 sm:px-6 py-2.5 sm:py-3 bg-ai-secondary hover:bg-ai-secondary/80 rounded-full text-white text-sm sm:text-base font-bold transition-all hover:scale-105 w-full sm:w-auto justify-center"
                >
                    <Navigation className="w-4 h-4 sm:w-5 sm:h-5 flex-shrink-0" />
                    <span className="whitespace-nowrap">Book Flights to Bagdogra</span>
                </a>
            </div>
        </div>
    );
};
